export const PHRASES = [
  { id: 1, firstHalf: "The owl of Minerva", trueEnding: "flies only at dusk." },
  { id: 2, firstHalf: "A cat may look", trueEnding: "at a king." },
  { id: 3, firstHalf: "The mills of God", trueEnding: "grind slowly but exceedingly fine." },
  { id: 4, firstHalf: "Fish and guests", trueEnding: "stink after three days." },
  { id: 5, firstHalf: "A whistling woman and a crowing hen", trueEnding: "bring luck to neither gods nor men." },
  { id: 6, firstHalf: "A hedge between", trueEnding: "keeps friendship green." },
  { id: 7, firstHalf: "The tongue that brings healing", trueEnding: "is a tree of life." },
  { id: 8, firstHalf: "A soft answer", trueEnding: "turns away wrath." },
  { id: 9, firstHalf: "The sleep of a laboring man", trueEnding: "is sweet." },
  { id: 10, firstHalf: "A good name", trueEnding: "is rather to be chosen than great riches." },
  { id: 11, firstHalf: "The race is not", trueEnding: "to the swift." },
  { id: 12, firstHalf: "Cast your bread upon the waters", trueEnding: "and it will return after many days." },
  { id: 13, firstHalf: "A threefold cord", trueEnding: "is not quickly broken." },
  { id: 14, firstHalf: "Iron sharpens iron", trueEnding: "as one man sharpens another." },
  { id: 15, firstHalf: "The lot is cast into the lap", trueEnding: "but its every decision is from the Lord." },
  { id: 16, firstHalf: "He who digs a pit", trueEnding: "shall fall into it." },
  { id: 17, firstHalf: "The borrower is", trueEnding: "servant to the lender." },
  { id: 18, firstHalf: "Better is a dry morsel", trueEnding: "with quietness than a house full of feasting with strife." },
  { id: 19, firstHalf: "A merry heart", trueEnding: "makes a cheerful countenance." },
  { id: 20, firstHalf: "The simple inherit", trueEnding: "folly." },
  { id: 21, firstHalf: "Beware of Greeks", trueEnding: "bearing gifts." },
  { id: 22, firstHalf: "A chain is only as strong", trueEnding: "as its weakest link." },
  { id: 23, firstHalf: "Don't cast pearls", trueEnding: "before swine." },
  { id: 24, firstHalf: "Familiarity breeds", trueEnding: "contempt." },
  { id: 25, firstHalf: "It's no use crying", trueEnding: "over spilled milk." },
  { id: 26, firstHalf: "When the cat's away", trueEnding: "the mice will play." },
  { id: 27, firstHalf: "A bird in the hand", trueEnding: "is worth two in the bush." },
  { id: 28, firstHalf: "Don't put the cart", trueEnding: "before the horse." },
  { id: 29, firstHalf: "Every dog has", trueEnding: "its day." },
  { id: 30, firstHalf: "Fools rush in", trueEnding: "where angels fear to tread." },
  { id: 31, firstHalf: "Familiarity breeds", trueEnding: "contempt." },
  { id: 32, firstHalf: "Great minds think", trueEnding: "alike." },
  { id: 33, firstHalf: "Honesty is", trueEnding: "the best policy." },
  { id: 34, firstHalf: "Ignorance is", trueEnding: "bliss." },
  { id: 35, firstHalf: "Just because you can", trueEnding: "doesn't mean you should." },
  { id: 36, firstHalf: "Knowledge is", trueEnding: "power." },
  { id: 37, firstHalf: "Laughter is", trueEnding: "the best medicine." },
  { id: 38, firstHalf: "Money can't buy", trueEnding: "happiness." },
  { id: 39, firstHalf: "Necessity is", trueEnding: "the mother of invention." },
  { id: 40, firstHalf: "Out of sight", trueEnding: "out of mind." },
  { id: 41, firstHalf: "Patience is", trueEnding: "a virtue." },
  { id: 42, firstHalf: "Quality over", trueEnding: "quantity." },
  { id: 43, firstHalf: "Revenge is", trueEnding: "a dish best served cold." },
  { id: 44, firstHalf: "Silence is", trueEnding: "golden." },
  { id: 45, firstHalf: "Time heals", trueEnding: "all wounds." },
  { id: 46, firstHalf: "Unity makes", trueEnding: "strength." },
  { id: 47, firstHalf: "Variety is", trueEnding: "the spice of life." },
  { id: 48, firstHalf: "Where there's smoke", trueEnding: "there's fire." },
  { id: 49, firstHalf: "You reap what", trueEnding: "you sow." },
  { id: 50, firstHalf: "Absence makes the heart", trueEnding: "grow fonder." },
  { id: 51, firstHalf: "Beauty is in the eye", trueEnding: "of the beholder." },
  { id: 52, firstHalf: "Clothes make", trueEnding: "the man." },
  { id: 53, firstHalf: "Don't judge a book", trueEnding: "by its cover." },
  { id: 54, firstHalf: "Every dog has", trueEnding: "its day." },
  { id: 55, firstHalf: "Fools rush in", trueEnding: "where angels fear to tread." },
  { id: 56, firstHalf: "God helps those", trueEnding: "who help themselves." },
  { id: 57, firstHalf: "Home is where", trueEnding: "the heart is." },
  { id: 58, firstHalf: "It's never too late", trueEnding: "to learn." },
  { id: 59, firstHalf: "Jack of all trades", trueEnding: "master of none." },
  { id: 60, firstHalf: "Keep your friends close", trueEnding: "and your enemies closer." },
  { id: 61, firstHalf: "Love is", trueEnding: "blind." },
  { id: 62, firstHalf: "Many hands make", trueEnding: "light work." },
  { id: 63, firstHalf: "Nothing ventured", trueEnding: "nothing gained." },
  { id: 64, firstHalf: "Old habits", trueEnding: "die hard." },
  { id: 65, firstHalf: "People who live in glass houses", trueEnding: "shouldn't throw stones." },
  { id: 66, firstHalf: "Quiet waters", trueEnding: "run deep." },
  { id: 67, firstHalf: "Red sky at night", trueEnding: "sailor's delight." },
  { id: 68, firstHalf: "Strike while", trueEnding: "the iron is hot." },
  { id: 69, firstHalf: "The apple doesn't fall far", trueEnding: "from the tree." },
  { id: 70, firstHalf: "United we stand", trueEnding: "divided we fall." },
  { id: 71, firstHalf: "Virtue is", trueEnding: "its own reward." },
  { id: 72, firstHalf: "Waste not", trueEnding: "want not." },
  { id: 73, firstHalf: "Youth is wasted", trueEnding: "on the young." },
  { id: 74, firstHalf: "A stitch in time", trueEnding: "saves nine." },
  { id: 75, firstHalf: "Birds of a feather", trueEnding: "flock together." },
  { id: 76, firstHalf: "Cleanliness is next", trueEnding: "to godliness." },
  { id: 77, firstHalf: "Don't look a gift horse", trueEnding: "in the mouth." },
  { id: 78, firstHalf: "Empty vessels", trueEnding: "make the most noise." },
  { id: 79, firstHalf: "First come", trueEnding: "first served." },
  { id: 80, firstHalf: "Give a man a fish and you feed him for a day", trueEnding: "teach him to fish and you feed him for a lifetime." },
  { id: 81, firstHalf: "Hope for the best", trueEnding: "but prepare for the worst." },
  { id: 82, firstHalf: "If wishes were horses", trueEnding: "beggars would ride." },
  { id: 83, firstHalf: "Judge not", trueEnding: "lest ye be judged." },
  { id: 84, firstHalf: "Keep your powder", trueEnding: "dry." },
  { id: 85, firstHalf: "Lightning never strikes", trueEnding: "the same place twice." },
  { id: 86, firstHalf: "Might makes", trueEnding: "right." },
  { id: 87, firstHalf: "Never say", trueEnding: "never." },
  { id: 88, firstHalf: "One man's trash", trueEnding: "is another man's treasure." },
  { id: 89, firstHalf: "Pen is mightier", trueEnding: "than the sword." },
  { id: 90, firstHalf: "Quick to judge", trueEnding: "quick to err." },
  { id: 91, firstHalf: "Rolling stones gather", trueEnding: "no moss." },
  { id: 92, firstHalf: "Still waters", trueEnding: "run deep." },
  { id: 93, firstHalf: "The best things in life", trueEnding: "are free." },
  { id: 94, firstHalf: "Under promise", trueEnding: "over deliver." },
  { id: 95, firstHalf: "Virtue has", trueEnding: "its own reward." },
  { id: 96, firstHalf: "When the going gets tough", trueEnding: "the tough get going." },
  { id: 97, firstHalf: "You can lead a horse to water", trueEnding: "but you can't make him drink." },
  { id: 98, firstHalf: "A fool and his money", trueEnding: "are soon parted." },
  { id: 99, firstHalf: "Better safe", trueEnding: "than sorry." },
  { id: 100, firstHalf: "Cross your bridges", trueEnding: "when you come to them." },
  { id: 101, firstHalf: "Don't cry over", trueEnding: "spilled milk." },
  { id: 102, firstHalf: "Experience is", trueEnding: "the best teacher." },
  { id: 103, firstHalf: "Fortune knocks at every man's door", trueEnding: "once in a lifetime." },
  { id: 104, firstHalf: "Good fences make", trueEnding: "good neighbors." },
  { id: 105, firstHalf: "Half a loaf", trueEnding: "is better than none." },
  { id: 106, firstHalf: "It takes two", trueEnding: "to tango." },
  { id: 107, firstHalf: "Just deserts", trueEnding: "are the sweetest." },
  { id: 108, firstHalf: "Keep your eyes", trueEnding: "on the prize." },
  { id: 109, firstHalf: "Life is what happens", trueEnding: "while you're making other plans." },
  { id: 110, firstHalf: "More haste", trueEnding: "less speed." },
  { id: 111, firstHalf: "No news", trueEnding: "is good news." },
  { id: 112, firstHalf: "One good turn", trueEnding: "deserves another." },
  { id: 113, firstHalf: "Pride comes", trueEnding: "before a fall." },
  { id: 114, firstHalf: "Quick and dirty", trueEnding: "gets the job done." },
  { id: 115, firstHalf: "Robbing Peter", trueEnding: "to pay Paul." },
  { id: 116, firstHalf: "Slow and steady", trueEnding: "wins the race." },
  { id: 117, firstHalf: "There's no place", trueEnding: "like home." },
  { id: 118, firstHalf: "Up the creek", trueEnding: "without a paddle." },
  { id: 119, firstHalf: "Variety is", trueEnding: "the spice of life." },
  { id: 120, firstHalf: "What goes up", trueEnding: "must come down." },
  { id: 121, firstHalf: "You made your bed", trueEnding: "now lie in it." },
  { id: 122, firstHalf: "A picture is worth", trueEnding: "a thousand words." },
  { id: 123, firstHalf: "Barking dogs", trueEnding: "seldom bite." },
  { id: 124, firstHalf: "Cut your coat", trueEnding: "according to your cloth." },
  { id: 125, firstHalf: "Don't put the cart", trueEnding: "before the horse." },
  { id: 126, firstHalf: "Every rose", trueEnding: "has its thorn." },
  { id: 127, firstHalf: "Fire is a good servant", trueEnding: "but a bad master." },
  { id: 128, firstHalf: "Give credit", trueEnding: "where credit is due." },
  { id: 129, firstHalf: "Hard work", trueEnding: "pays off." },
  { id: 130, firstHalf: "In for a penny", trueEnding: "in for a pound." },
  { id: 131, firstHalf: "Just in the nick", trueEnding: "of time." },
  { id: 132, firstHalf: "Keep your chin", trueEnding: "up." },
  { id: 133, firstHalf: "Little strokes", trueEnding: "fell great oaks." },
  { id: 134, firstHalf: "Mind your own", trueEnding: "business." },
  { id: 135, firstHalf: "Never look back", trueEnding: "you're not going that way." },
  { id: 136, firstHalf: "One swallow", trueEnding: "doesn't make a summer." },
  { id: 137, firstHalf: "Put your money", trueEnding: "where your mouth is." },
  { id: 138, firstHalf: "Quiet as", trueEnding: "a mouse." },
  { id: 139, firstHalf: "Right as", trueEnding: "rain." },
  { id: 140, firstHalf: "Smooth as", trueEnding: "silk." },
  { id: 141, firstHalf: "The die", trueEnding: "is cast." },
  { id: 142, firstHalf: "Under the weather", trueEnding: "feeling ill." },
  { id: 143, firstHalf: "Variety keeps life", trueEnding: "interesting." },
  { id: 144, firstHalf: "When pigs", trueEnding: "fly." },
  { id: 145, firstHalf: "You can't make an omelet", trueEnding: "without breaking eggs." },
  { id: 146, firstHalf: "A leopard can't change", trueEnding: "its spots." },
  { id: 147, firstHalf: "Better the devil you know", trueEnding: "than the devil you don't." },
  { id: 148, firstHalf: "Cut to", trueEnding: "the chase." },
  { id: 149, firstHalf: "Don't throw the baby out", trueEnding: "with the bathwater." },
  { id: 150, firstHalf: "Every little bit", trueEnding: "helps." }
]

export function getRandomPhrase(excludeIds = []) {
  const availablePhrases = PHRASES.filter(p => !excludeIds.includes(p.id))
  if (availablePhrases.length === 0) return PHRASES[Math.floor(Math.random() * PHRASES.length)]
  return availablePhrases[Math.floor(Math.random() * availablePhrases.length)]
}