export const SAYINGS = [
  { "id": 1, "firstHalf": "A feast uncovers", "trueEnding": "a European's wooden leg", "origin": "Oji—West African" },
  { "id": 2, "firstHalf": "Wood already touched by fire", "trueEnding": "is not hard to set alight", "origin": "African" },
  { "id": 3, "firstHalf": "Even the lion protects himself", "trueEnding": "against flies", "origin": "African" },
  { "id": 4, "firstHalf": "A person is a person", "trueEnding": "because of other people", "origin": "South African" },
  { "id": 5, "firstHalf": "If you think you're too small to make a difference", "trueEnding": "try spending the night with a mosquito", "origin": "African" },
  { "id": 6, "firstHalf": "A fortune gone to", "trueEnding": "hashed fish", "origin": "Japanese" },
  { "id": 7, "firstHalf": "The harelip is taken", "trueEnding": "for a dimple", "origin": "Japanese" },
  { "id": 8, "firstHalf": "Between truth and falsehood, the distance is", "trueEnding": "four fingers", "origin": "Hindustani" },
  { "id": 9, "firstHalf": "When the winds of change blow, some people build walls", "trueEnding": "and others build windmills", "origin": "Chinese" },
  { "id": 10, "firstHalf": "A dog bites", "trueEnding": "Lü Dongbin", "origin": "Chinese" },
  { "id": 11, "firstHalf": "A ground sweat", "trueEnding": "cures all diseases", "origin": "English" },
  { "id": 12, "firstHalf": "All goeth down", "trueEnding": "Gutter Lane", "origin": "English" },
  { "id": 13, "firstHalf": "That will happen in the week of", "trueEnding": "four Thursdays", "origin": "Louisiana Creole" },
  { "id": 14, "firstHalf": "Not my circus", "trueEnding": "not my monkeys", "origin": "Polish" },
  { "id": 15, "firstHalf": "God gives nuts", "trueEnding": "to the man with no teeth", "origin": "Arabic" },
  { "id": 16, "firstHalf": "He who pelts another with pebbles", "trueEnding": "asks for rocks in return", "origin": "Nigerian" },
  { "id": 17, "firstHalf": "Whoever hunts with a cat", "trueEnding": "will be hunted by mice", "origin": "Brazilian" },
  { "id": 18, "firstHalf": "Shrimp that falls asleep", "trueEnding": "is carried by the current", "origin": "Mexican" },
  { "id": 19, "firstHalf": "To each chapel", "trueEnding": "its own party", "origin": "Mexican" },
  { "id": 20, "firstHalf": "Where they love you a lot", "trueEnding": "don't go often", "origin": "Spanish" },
  { "id": 21, "firstHalf": "A creaking gate", "trueEnding": "hangs the longest", "origin": "English" },
  { "id": 22, "firstHalf": "The beard will pay", "trueEnding": "for the shaving", "origin": "English" },
  { "id": 23, "firstHalf": "A loyal heart may be landed", "trueEnding": "under Traitor's bridge", "origin": "English" },
  { "id": 24, "firstHalf": "Fine words butter", "trueEnding": "no parsnips", "origin": "English" },
  { "id": 25, "firstHalf": "A new broom", "trueEnding": "sweeps clean", "origin": "English" },
  { "id": 26, "firstHalf": "The hand is shallow", "trueEnding": "but the throat is deep", "origin": "New Zealand" },
  { "id": 27, "firstHalf": "A shoe of silver", "trueEnding": "makes iron soft", "origin": "Marathi" },
  { "id": 28, "firstHalf": "To have tomatoes", "trueEnding": "on your eyes", "origin": "German" },
  { "id": 29, "firstHalf": "To slide in on", "trueEnding": "a shrimp sandwich", "origin": "Swedish" },
  { "id": 30, "firstHalf": "To have a wide", "trueEnding": "face", "origin": "Japanese" },
  { "id": 31, "firstHalf": "To jump from the rooster", "trueEnding": "to the donkey", "origin": "French" },
  { "id": 32, "firstHalf": "To feed a donkey", "trueEnding": "sponge cake", "origin": "Portuguese" },
  { "id": 33, "firstHalf": "To let a frog", "trueEnding": "out of your mouth", "origin": "Finnish" },
  { "id": 34, "firstHalf": "Into the mouth", "trueEnding": "of the wolf", "origin": "Italian" },
  { "id": 35, "firstHalf": "The one who is not in the dance", "trueEnding": "says the drum is not loud enough", "origin": "Ghanian" },
  { "id": 36, "firstHalf": "A roaring lion", "trueEnding": "kills no game", "origin": "African" },
  { "id": 37, "firstHalf": "The moon moves slowly", "trueEnding": "but it crosses the town", "origin": "African" },
  { "id": 38, "firstHalf": "A single bracelet", "trueEnding": "does not jingle", "origin": "Congolese" },
  { "id": 39, "firstHalf": "When a needle falls into a deep well", "trueEnding": "many people will look into the well, but few will be willing to go down after it", "origin": "Ethiopian" },
  { "id": 40, "firstHalf": "A child's fingers", "trueEnding": "are not scalded by a piece of hot yam which his mother puts into his palm", "origin": "Nigerian" },
  { "id": 41, "firstHalf": "The ruin of a nation", "trueEnding": "begins in the homes of its people", "origin": "Ashanti" },
  { "id": 42, "firstHalf": "A man who is trampled to death by an elephant", "trueEnding": "is a man who is blind and deaf", "origin": "Kenyan" },
  { "id": 43, "firstHalf": "The chameleon changes color", "trueEnding": "to match the earth, the earth does not change color to match the chameleon", "origin": "Ghanian" },
  { "id": 44, "firstHalf": "A wise man who knows proverbs", "trueEnding": "reconciles difficulties", "origin": "Yoruba" },
  { "id": 45, "firstHalf": "To get lost is to", "trueEnding": "learn the way", "origin": "African" },
  { "id": 46, "firstHalf": "The best way to eat an elephant", "trueEnding": "is to cut him up into little pieces", "origin": "African" },
  { "id": 47, "firstHalf": "A restless foot", "trueEnding": "eventually steps on a snake", "origin": "African" },
  { "id": 48, "firstHalf": "A letter from the heart", "trueEnding": "can be read on the face", "origin": "Kenyan" },
  { "id": 49, "firstHalf": "If you are building a house and a nail breaks", "trueEnding": "do you stop building or do you change the nail?", "origin": "Rwandan" },
  { "id": 50, "firstHalf": "A man who pays respect to the great", "trueEnding": "paves his own way for greatness", "origin": "Nigerian" },
  { "id": 51, "firstHalf": "An army of sheep", "trueEnding": "led by a lion would defeat an army of lions led by a sheep", "origin": "Arabian" },
  { "id": 52, "firstHalf": "The whisper of a pretty girl", "trueEnding": "can be heard further than the roar of a lion", "origin": "Arabian" },
  { "id": 53, "firstHalf": "A single stick", "trueEnding": "is easily broken, but a bundle of sticks is not", "origin": "Asian" },
  { "id": 54, "firstHalf": "The man who moves a mountain", "trueEnding": "begins by carrying away small stones", "origin": "Chinese" },
  { "id": 55, "firstHalf": "A closed mind", "trueEnding": "is like a closed book; just a block of wood", "origin": "Chinese" },
  { "id": 56, "firstHalf": "The best time to plant a tree", "trueEnding": "was 20 years ago. The second best time is now", "origin": "Chinese" },
  { "id": 57, "firstHalf": "A bird does not sing", "trueEnding": "because it has an answer. It sings because it has a song", "origin": "Chinese" },
  { "id": 58, "firstHalf": "The fish sees the bait", "trueEnding": "not the hook", "origin": "Chinese" },
  { "id": 59, "firstHalf": "If you want happiness for an hour", "trueEnding": "take a nap. If you want happiness for a day, go fishing. If you want happiness for a year, inherit a fortune. If you want happiness for a lifetime, help somebody", "origin": "Chinese" },
  { "id": 60, "firstHalf": "To know the road ahead", "trueEnding": "ask those coming back", "origin": "Chinese" },
  { "id": 61, "firstHalf": "A fall into a ditch", "trueEnding": "makes you wiser", "origin": "Chinese" },
  { "id": 62, "firstHalf": "The poor man's vineyard", "trueEnding": "is full of words", "origin": "Chilean" },
  { "id": 63, "firstHalf": "You can't get blood", "trueEnding": "from a turnip", "origin": "English" },
  { "id": 64, "firstHalf": "The sea is the same", "trueEnding": "everywhere", "origin": "English" },
  { "id": 65, "firstHalf": "A watched pot", "trueEnding": "never boils", "origin": "English" },
  { "id": 66, "firstHalf": "If you want to know what a man is like", "trueEnding": "take a good look at how he treats his inferiors, not his equals", "origin": "English" },
  { "id": 67, "firstHalf": "The hands that help", "trueEnding": "are holier than the lips that pray", "origin": "English" },
  { "id": 68, "firstHalf": "A smooth sea", "trueEnding": "never made a skilled sailor", "origin": "English" },
  { "id": 69, "firstHalf": "The darkest hour", "trueEnding": "is just before the dawn", "origin": "English" },
  { "id": 70, "firstHalf": "When the last tree is cut down, the last fish eaten, and the last stream poisoned", "trueEnding": "you will realize that you cannot eat money", "origin": "Cree" },
  { "id": 71, "firstHalf": "A healthy man is a successful man", "trueEnding": "even if he is not a king", "origin": "Ethiopian" },
  { "id": 72, "firstHalf": "The word of a friend", "trueEnding": "makes you cry; the word of an enemy, makes you laugh", "origin": "Ethiopian" },
  { "id": 73, "firstHalf": "A house without a woman", "trueEnding": "is a house without a foundation", "origin": "Ethiopian" },
  { "id": 74, "firstHalf": "When the shepherd is angry with his sheep", "trueEnding": "he sends them to a dangerous pasture", "origin": "Ethiopian" },
  { "id": 75, "firstHalf": "A fool and his water", "trueEnding": "are soon parted", "origin": "Ethiopian" },
  { "id": 76, "firstHalf": "The dog's kennel", "trueEnding": "is not a place to keep a sausage", "origin": "Finnish" },
  { "id": 77, "firstHalf": "A summer with a daughter", "trueEnding": "is a summer without a break", "origin": "Finnish" },
  { "id": 78, "firstHalf": "The one who asks", "trueEnding": "is not a fool", "origin": "Finnish" },
  { "id": 79, "firstHalf": "Even a small star", "trueEnding": "shines in the darkness", "origin": "Finnish" },
  { "id": 80, "firstHalf": "It's better to be a coward for a minute", "trueEnding": "than dead for the rest of your life", "origin": "Irish" },
  { "id": 81, "firstHalf": "A little fire that warms", "trueEnding": "is better than a big fire that burns", "origin": "Irish" },
  { "id": 82, "firstHalf": "It is in the shelter of each other", "trueEnding": "that the people live", "origin": "Irish" },
  { "id": 83, "firstHalf": "You'll never plow a field", "trueEnding": "by turning it over in your mind", "origin": "Irish" },
  { "id": 84, "firstHalf": "A silent mouth", "trueEnding": "is sweet to hear", "origin": "Irish" },
  { "id": 85, "firstHalf": "A kind word", "trueEnding": "never broke anyone's mouth", "origin": "Irish" },
  { "id": 86, "firstHalf": "The cat is a good friend", "trueEnding": "but she scratches", "origin": "Italian" },
  { "id": 87, "firstHalf": "If you have a lot of butter", "trueEnding": "you can put it on your bread", "origin": "Italian" },
  { "id": 88, "firstHalf": "He who goes to bed without dinner", "trueEnding": "wakes up without credit", "origin": "Italian" },
  { "id": 89, "firstHalf": "After the rain", "trueEnding": "comes the good weather", "origin": "Italian" },
  { "id": 90, "firstHalf": "At the end of the game", "trueEnding": "the king and the pawn go into the same box", "origin": "Italian" },
  { "id": 91, "firstHalf": "The morning has gold", "trueEnding": "in its mouth", "origin": "Italian" },
  { "id": 92, "firstHalf": "If you don't have a dog", "trueEnding": "you hunt with a cat", "origin": "Italian" },
  { "id": 93, "firstHalf": "The wolf changes his coat", "trueEnding": "but not his vice", "origin": "Italian" },
  { "id": 94, "firstHalf": "When the pear is ripe", "trueEnding": "it will fall", "origin": "Italian" },
  { "id": 95, "firstHalf": "A beautiful frame", "trueEnding": "does not make the picture", "origin": "Italian" },
  { "id": 96, "firstHalf": "The shrimp that sleeps", "trueEnding": "is carried away by the current", "origin": "Jamaican" },
  { "id": 97, "firstHalf": "The higher the monkey climbs", "trueEnding": "the more he is exposed", "origin": "Jamaican" },
  { "id": 98, "firstHalf": "A new broom sweeps clean", "trueEnding": "but the old one knows the corners", "origin": "Jamaican" },
  { "id": 99, "firstHalf": "The frog's own croak", "trueEnding": "betrays him", "origin": "Jamaican" },
  { "id": 100, "firstHalf": "If you want to know your friend", "trueEnding": "boil a pot of peas for him", "origin": "Jamaican" }
];

export function getRandomSaying(excludeIds = []) {
  const availableSayings = SAYINGS.filter(p => !excludeIds.includes(p.id))
  if (availableSayings.length === 0) {
    return null
  }
  
  // Use cryptographically strong randomness for better distribution
  const randomIndex = Math.floor(Math.random() * availableSayings.length)
  return availableSayings[randomIndex]
}